name: Build and release binary
on:
  push:
    tags:
      - 'v*'
    paths:
      - '.github/workflows/build.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"
          cache: true
      - name: Get version
        id: get_version
        run: |
          echo VERSION=$(echo $GITHUB_REF | cut -d / -f 3) >> $GITHUB_OUTPUT
          echo IS_PRERELEASE=$(echo $GITHUB_REF | grep -q "-" && echo true || echo false) >> $GITHUB_OUTPUT
      - name: Replace version
        run: |
          sed -i "s/const Version = \"0.0.0\"/const Version = \"${{ steps.get_version.outputs.VERSION }}\"/g" ./pkg/pjsekaioverlay/version.go
      - name: Create package directory
        run: mkdir -p release
      - name: Build binary
        run: go build -o release/pjsekai-overlay-MULTI.exe .
        env:
          GOOS: windows
          GOARCH: amd64
      - name: Copy assets
        run: cp -r assets release/assets
      - name: Build zip
        run: cd release && zip -r ../pjsekai-overlay-MULTI.zip .
